branch-defaults:
  default:
    environment: devLawcall
environment-defaults:
  devLawcall:
    branch: null
    repository: null
global:
  application_name: lawcall_api
  default_ec2_keyname: '123'
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
