# Generated by Django 5.0.2 on 2025-08-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadquery',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='leadquery',
            name='stage',
        ),
        migrations.AddField(
            model_name='leadquery',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ib.business'),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='city',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='country',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='query',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='state',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='status',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='email',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='leadquery',
            name='phone',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='PlanQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=500)),
                ('stage', models.CharField(default='', max_length=500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lead_query/attachment')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ib.customuser')),
            ],
        ),
    ]
