# Generated by Django 5.0.2 on 2025-08-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0004_rename_my_id_customuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='my_id',
        ),
    ]
