# Generated by Django 5.0.2 on 2025-08-14 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0005_rename_user_id_customuser_my_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
