# Generated by Django 5.0.2 on 2025-08-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0006_customuser_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='phone',
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
