# Generated by Django 5.0.2 on 2025-08-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0006_customuser_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadquery',
            name='interested',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='priority',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='leadquery',
            name='tag',
            field=models.TextField(default=''),
        ),
    ]
