# Generated by Django 5.0.2 on 2025-08-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0007_remove_business_phone_business_whatsapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.CharField(default='', max_length=500)),
                ('note', models.CharField(default='', max_length=500)),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=500)),
                ('stage', models.CharField(default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='planquery',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='planquery',
            name='plan',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='planquery',
            name='transaction_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
