# Generated by Django 5.0.2 on 2025-08-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0008_quate_planquery_name_planquery_plan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='BusinessPlan',
        ),
    ]
