# Generated by Django 5.0.2 on 2025-08-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ib', '0003_customuser_groups_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='my_id',
            new_name='user_id',
        ),
    ]
